language: android
jdk:
    - oraclejdk7
    - openjdk7
android:
  components:
    - platform-tools
    - tools
    - build-tools-22.0.1
    - android-22
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - extra-android-support
before_install:
    - sudo /etc/init.d/mysql stop
    - sudo /etc/init.d/postgresql stop
install:
    - chmod +x ./gradlew; ls -l gradlew; ./gradlew wrapper -v
script: ./gradlew assembleDebug
